GBL-483-Actions-for-jira-comment,assignee,link
gblearning/gbl-gha pull request #12
Opened 2022-09-01 14:24 UTC by Cookieees

2022-09-01 15:16 UTC, blake-r submitted a review, later dismissed
Вопросы по работоспособности кавычек в кавычках, плюс просьба по форматированию.

2022-09-02 07:30 UTC, Cookieees commented on jira-assignee/action.yml
> +        assignee_body=$(cat << EOT
не смогу кинуть ссылкой на правильный ресурс, но я помню что это просто делимитеры here-doc'а, то есть там можно хоть `cookieees` написать, лишь бы а) не было пробелов и б) в начале и конце блока стояли посимвольно идентичные делимитеры.
А различные я использую, так как натыкался на ошибки, используя EOF. Возможно, потому что github, раскрывая `run` из yml использует как раз EOF, из-за чего встречаемый на пути мой(!) EOF считывается как закрывающий, а может и по другим причинам. В любом случае это как перестраховка, про которую ты сегодня говорил

2022-09-02 07:32 UTC, Cookieees commented on jira-comment/action.yml
> +        comment="${{ inputs.comment }}"
чтобы длинная github переменная была только в одном месте, а в остальном коде короткий `$comment`

2022-09-02 07:32 UTC, blake-r commented on jira-assignee/action.yml
> +        assignee_body=$(cat << EOT
Да, тут любой идентификатор. Но мне нужна осмысленность. :)

2022-09-02 07:33 UTC, blake-r commented on jira-comment/action.yml
> +        comment="${{ inputs.comment }}"
В "остальном" коде это используется один раз.
Ты код смотришь или поводы не делать ищешь? :)

2022-09-02 07:37 UTC, Cookieees commented on jira-assignee/action.yml
> +          --data "${assignee_body}" \
вполне себе работает. Как и в других местах с JSON телом
![image](https://user-images.githubusercontent.com/32365962/188084278-5f14314d-63e4-4993-87d1-66827eca41fd.png)

2022-09-02 07:58 UTC, Cookieees commented on jira-issue-linking/action.yml
> +        for outward_issue in ${{ inputs.outward_issues }}; do
Да, всё прекрасно
https://jira.netology-group.ru/browse/GBL-461
https://github.com/gblearning/gbl-games-portal/runs/8151762581?check_suite_focus=true
![image](https://user-images.githubusercontent.com/32365962/188087733-b66c78bf-bc38-444f-9998-c53d10c52a76.png)

2022-09-02 12:03 UTC, blake-r requested changes

2022-09-02 12:03 UTC, blake-r commented on jira-assignee/action.yml
> +        assignee_body=$(cat << EOT
Так что такое EOT?

2022-09-02 12:03 UTC, blake-r commented on jira-comment/action.yml
> +        comment="${{ inputs.comment }}"
Так зачем тут переменная?

2022-09-02 13:34 UTC, Cookieees commented on jira-assignee/action.yml
> +        assignee_body=$(cat << EOT
Это делимитер, отличающийся от EOL и EOF. Главное чтобы он не совпал со внешним, если таковой есть. Поэтому они и разные. Это никак не расшифровывется, но похоже на привычные EOL и EOF, поэтому их назначение понятно.
Видимо я тебя не понимаю, предложи, пожалуйста, свой вариант?

2022-09-02 13:36 UTC, Cookieees commented on jira-comment/action.yml
> +        comment="${{ inputs.comment }}"
Ты прав, здесь и сейчас - один раз. Я не считал, а просто подумал на ходу и сделал на всякий случай.
Переменную убрал.

2022-09-02 13:40 UTC, blake-r requested changes

2022-09-02 13:40 UTC, blake-r commented on jira-issue-find/action.yml
> +          ISSUE_KEYS=( $(curl -s \
1. Лучше использовать такой же подход как везде.
Сейчас при ошибках Jira ты делаешь ещё хуже и не показываешь что реально случилось - по цепочке остальные команды тоже будет не понимать что случилось. Нужен финт с http_code.

2. Для локальных переменных лучше использовать нижний регистр. Верхний только если они экспортируются как переменных окружения.

2022-09-05 10:59 UTC, blake-r requested changes

2022-09-05 10:59 UTC, blake-r commented on jira-issue-find/action.yml
> +    description: Finded issue keys
```suggestion
    description: Found issue keys
```

2022-09-05 10:59 UTC, blake-r commented on jira-issue-find/action.yml
> +  keys_num:
```suggestion
  limit:
```

2022-09-05 10:59 UTC, blake-r commented on jira-issue-find/action.yml
> +inputs:
+ "fields"

2022-09-05 10:59 UTC, blake-r commented on jira-issue-find/action.yml
> +            "${{ inputs.jira_url }}/rest/api/2/search/"
Добавить `--data-urlencode 'maxResults=${{ inputs.limit }}'`

2022-09-05 14:57 UTC, blake-r requested changes

2022-09-05 14:57 UTC, blake-r commented on jira-issue-find/action.yml
> +            echo "${http_code} $(cat output_filename)"
Нужно ещё выходит типа `exit 1`.
Ты сейчас скрываешь ошибки.
Будешь потом дебажить скрипты где-то ещё, вместо того чтобы на запрос посмотреть.

2022-09-06 08:08 UTC, blake-r approved these changes

2022-09-06 14:46 UTC, merged