Gbl 490 jira custom transition
gblearning/gbl-gha pull request #15
Opened 2022-09-19 08:40 UTC by Cookieees

2022-09-19 10:01 UTC, Cookieees commented
> Логика в принципе верная, но делает реализацию сложной и опасной по багам.
Я это всё тоже понимал с самого начала. Но как разделить на блоки/шаги я не придумал

2022-09-19 10:19 UTC, blake-r requested changes
Коренным образом логика не поменялась.
Давай отложим до созвона, я объясню пожелание.

2022-09-19 10:19 UTC, blake-r commented on jira-issue-transition/action.yml
> +            echo "inputs.status_name as desired status should be specified too"
Не обязательно если из текущего статуса можно сразу перейти на желаемый.

2022-09-19 14:58 UTC, blake-r requested changes

2022-09-19 14:58 UTC, blake-r commented on jira-issue-transition/action.yml
> +            echo "inputs.status_name as desired status should be specified too"
Договорились убрать input.transition_name если не используется - тогда эта проверка станет не нужна.

Где у нас используется transition_name?

2022-09-19 14:58 UTC, blake-r commented on jira-issue-transition/action.yml
> +            '${{ inputs.jira_url }}/rest/api/2/issue/${{ inputs.issue_key }}?fields=status' \
👍🏻

2022-09-19 14:58 UTC, blake-r commented on jira-issue-transition/action.yml
> +        echo "WORKFLOW=$workflow" | tee -a $GITHUB_ENV
В моем случае это был вынужденный трюк для передачи переменной из шага N, когда N неизвестно. В остальных случаях пользуемся стандартным механизмом steps.<>.outputs.<>.

Также лучше уже здесь проставить workflow равным status_name при нужных условиях.

2022-09-19 14:58 UTC, blake-r commented on jira-issue-transition/action.yml
> +        # Get current issue transitions
Это теперь незачем, тикет должен быть уже в нужном статусе.

2022-09-19 15:11 UTC, Cookieees commented on jira-issue-transition/action.yml
> +        echo "WORKFLOW=$workflow" | tee -a $GITHUB_ENV
механизм `steps.<>.outputs.<>.` умеет только в строки. Но если мы попробуем положить именно список статусов как строку и потом из этой строки попытаться сделать массив для возможности итерации, мы получим для каждого слова отдельную итерацию (н-р: `Ready` -> `for` -> `Release`) ...
И тут я понял что совсем не прав, ибо переменная среды не может быть bash массивом 😢.
А значит при передаче между шагами её надо обратно в строку с разделителями упаковывать, а в следующем шаге снова разбирать через `IFS=',' read ...`

2022-09-19 15:12 UTC, Cookieees commented on jira-issue-transition/action.yml
> +        # Get current issue transitions
упс, мало удалил) Оставил лишнего. Да, разумеется, шаг совсем лишний

2022-09-19 15:48 UTC, Cookieees commented on jira-issue-transition/action.yml
> +        echo "WORKFLOW=$workflow" | tee -a $GITHUB_ENV
Изменил процесс, согласно изложенным соображениям

2022-09-20 13:52 UTC, blake-r requested changes

2022-09-20 13:52 UTC, blake-r commented on jira-issue-transition/action.yml
> +  current_status:
Точно ли возвращаемое значение нигде не используется как "outputs.status"?

2022-09-20 13:52 UTC, blake-r commented on jira-issue-transition/action.yml
> +          workflow=( "${{ inputs.status_name }}" )
Здесь должно быть два элемента - текущий статус и желаемый.

Это позволит сильно упросить елочку условие 82 строки.

2022-09-20 13:52 UTC, blake-r commented on jira-issue-transition/action.yml
> +          fi
```suggestion
          if ! $found; then
            if [ "$status" == "$current_status" ]; then
              found=true
            fi
            continue
          fi
```

2022-09-20 13:52 UTC, blake-r commented on jira-issue-transition/action.yml
> +              -d"{\"transition\": {\"id\": \"$transition_id\"}, \"update\": ${{ inputs.update_json }} }" \
Я и забыл про update_json. :(

Каждый раз его применять не надо - ожидания вызывающего будут, что он применяется только один раз при переключении в нужный статус.

Сделать добавление update_json условным по [ "$status" == "$status_name" ]`, пожалуйста.

2022-09-20 14:47 UTC, blake-r requested changes

2022-09-20 14:47 UTC, blake-r commented on jira-issue-transition/action.yml
> +  current_status:
Не получил ответа здесь.

2022-09-20 14:47 UTC, blake-r commented on jira-issue-transition/action.yml
> +              update_field=", \"update\": ${{ inputs.update_json }}"
Рано. Должен быть не current_status, а status_name (требуемый).

Ты сейчас фактически не изменил прошлую логику работы.

2022-09-20 14:52 UTC, Cookieees commented on jira-issue-transition/action.yml
> +              update_field=", \"update\": ${{ inputs.update_json }}"
а, блин. Уже теряю концентрацию. Думал что ты просто опечатался, не стал уточнять и подумал не туда(

2022-09-20 14:54 UTC, blake-r approved these changes

2022-09-20 14:55 UTC, merged