GBL-706 Show errors outside spoiler
gblearning/gbl-gha pull request #43
Opened 2022-12-08 13:52 UTC by Cookieees

Мне не нравится идея вложенного открывания файла в разных режимах, но комбинированного режима у `open()` нету, а ничего другого я не придумал. Впрочем это работает. И на файлах в тысячу строк отрабатывает мгновенно

2022-12-08 13:58 UTC, blake-r requested changes

2022-12-08 13:58 UTC, blake-r commented on gha/bin/comment-error-to-pr.py
> +ERRORS_STR = ''
Забытая переменная?

2022-12-08 13:58 UTC, blake-r commented on gha/bin/comment-error-to-pr.py
> +                    file.write(f"\n```\n</details>\n\n```\n{error_entries}```\n")
```suggestion
                    error_entries = []
                    with open(logfile, "r") as file_read:               # Read all lines in a list in read mode
                        lines = file_read.readlines()
                        for line in lines:
                            if line.find(ERROR_LOGS_KEY) != -1:
                                error_entries.append(line)
                    file.write(f"\n```\n</details>\n\n```\n{"\n".join(error_entries)}```\n")
```

2022-12-08 14:05 UTC, Cookieees commented on gha/bin/comment-error-to-pr.py
> +ERRORS_STR = ''
упс

2022-12-08 14:10 UTC, blake-r requested changes
У меня дежа-вю.

2022-12-08 14:10 UTC, blake-r commented on gha/bin/comment-error-to-pr.py
> +                    file.write(f"\n```\n</details>\n\n```\n{error_entries}```\n")
```suggestion
                    error_entries = []
                    with open(logfile, "r") as file_read:               # Read all lines in a list in read mode
                        lines = file_read.readlines()
                        for line in lines:
                            if line.find(ERROR_LOGS_KEY) != -1:
                                error_entries.append(line)
                    file.write(f"\n```\n</details>\n\n```\n{"\n".join(error_entries)}```\n")
```

2022-12-09 06:59 UTC, blake-r approved these changes

2022-12-09 07:24 UTC, merged