GBL-746 Post cancelled release scope to new Jira release
gblearning/gbl-gha pull request #59
Opened 2022-12-28 13:17 UTC by Cookieees

При создании нового релизного тикета, если предыдущий релиз отменён, в комменты постится scope из всех тикетов только ПОСЛЕ отменённого релиза.
Линкуются по прежнему все тикеты, начиная с прошлого успешного релиза.

2022-12-28 13:38 UTC, Cookieees commented
Примет логов (локальный запуск, дебаговые значения некоторых переменных)

```
Repository name: gbl-mathmagic-unity
JIRA project name: GBLDM
Head: heads/release     
Sha: 63c912254e9f10af019daa9faa3ceb663bc2ff14
Commit date: 2022-12-23
Commit monday: 2022-12-19
Commit count since monday: 14
Commit version: v1.51.14
Release ticket: GBLDM-1751
Switch status from "ready for publication" to "Cancelled" using "Отменить"
Switch status from "Cancelled" to "In Progress" using "Восстановить"      
Switch status from "In Progress" to "Uploading to Staging" using "Готово" 
Release version regex: \bv(\d+\.\d+\.\d+)\b                               
Previous release ticket: GBLDM-1693                        
Previous release status: Done                              
Previous release version: v1.50.16                         
Add link "Gantt End to Start" from GBLDM-1693 to GBLDM-1751
Compare e03109d1c9c88c718d7c22c6d1615f2a9d69aa71..63c912254e9f10af019daa9faa3ceb663bc2ff14
Release scope (14): GBLDM-1632, GBLDM-1692, GBLDM-1687, GBLDM-1699, GBLDM-1696, GBLDM-1698, GBLDM-1694, GBLDM-1711, GBLDM-1721, GBLDM-1741, GBLDM-1742, GBLDM-1709, GBLDM-1743, GBLDM-1750
Remove link to GBLDM-1689
Add link to GBLDM-1632   
Add link to GBLDM-1743   
CANCELLED SHA: 63c912254e9f10af019daa9faa3ceb663bc2ff14
Compare e03109d1c9c88c718d7c22c6d1615f2a9d69aa71..63c912254e9f10af019daa9faa3ceb663bc2ff14
Latest (cancelled) release scope contains 14 tasks:
  1. GBLDM-1632 Change id in battle_task_result event (#803)      
  2. GBLDM-1692 set rotaton subscription on view activation (#805)
  3. GBLDM-1687 fix history auth flow (#807)                      
  4. GBLDM-1699 add language switching (#808)                     
  5. GBLDM-1696 update paywalls to sprite set (#809)              
  6. GBLDM-1698 confirmWindowView refactoring (#811)              
  7. GBLDM-1694 paywalls 3 and 4 (#812)                           
  8. GBLDM-1711 add battle blocker to incubator (#813)            
  9. GBLDM-1721 add english sounds to 2iloc config (#814)
  10. GBLDM-1741 remove debud method (#815)
  11. GBLDM-1742 turn code verification prefab off, check object active before analyti… (#817)
  12. GBLDM-1709 remove outdated windows (#816)
  13. GBLDM-1743 dont show paywall on click, if has battles (#818)
  14. GBLDM-1750 fix day counting and paywall opening (#819)

JIRA board id: 474
Found project sprints: 2022/52, 2023/2, 2023/3
Release has sprint "2022/52" already
Looks good
```

2022-12-28 13:39 UTC, blake-r requested changes

2022-12-28 13:39 UTC, blake-r commented on gha/bin/release-init.py
> +                    if self.apply:
👍🏻 

Спасибо!

2022-12-28 13:39 UTC, blake-r commented on gha/bin/release-init.py
> +        # Check for previous cancelled release
А вот дальше что-то совсем дичь.

- версию прошлого релизного тикета лучше сразу же парсить, как только нашли соответствующий тикет;
- for tag in repo_tags - уже есть один такой цикл, второго не нужно - нужно перенести поиск cancelled_sha туда;
- получение списка коммитов в diff нужно вынести в функцию и использовать два раза, а не писать два раза почти один и тот же код - поддерживать дубли очень муторно.

2022-12-29 08:07 UTC, blake-r requested changes

2022-12-29 08:07 UTC, blake-r commented on gha/bin/release-init.py
> +                    issue=IssueLinkType.Relates,
WTF?

2022-12-29 08:07 UTC, blake-r commented on gha/bin/release-init.py
> +        if last_cancelled_release:
Прошлый релиз всегда есть - отменённый или опубликованный.

```suggestion
        if last_release:
```

2022-12-29 08:07 UTC, blake-r commented on gha/bin/release-init.py
> +                if title == "Merge branch 'main' into release":
Это лишнее, даже пока наоборот я бы хотел видеть такие вещи.

2022-12-29 08:07 UTC, blake-r commented on gha/bin/release-init.py
> +            self.log.info(f'Latest (cancelled) release scope contains {len(cancelled_release_scope)} tasks:')
Да кто сказал, что last всегда будет cancelled? Или cancelled или published - сегодня утром я так говорил.

```suggestion
            self.log.info(f'Latest release scope contains {len(cancelled_release_scope)} tasks:')
```

2022-12-29 08:07 UTC, blake-r commented on gha/bin/release-init.py
> +            comment_body = PREVIOUS_RELEASE_TASKS % dict(
Имя константы непонятное, как будто она перечисляет какие-то задачи.

```suggestion
            comment_body = RELEASE_SCOPE_COMMENT_BODY % dict(
```

2022-12-29 08:07 UTC, blake-r commented on gha/bin/release-init.py
> +        return self.repo.compare(sha1, sha2).commits
Шутишь? Вот ради строчки 1:1 ты вынес это в отдельную функцию?

2022-12-29 08:07 UTC, blake-r commented on gha/bin/release-init.py
> +            if repo_name != "gbl-games-portal"
Нет ли у тебя констант для имён репозиториев?

2022-12-29 08:07 UTC, blake-r commented on gha/bin/release-init.py
> +                f"Cancelled release {issue.key} summary does not contain version")
А уж здесь-то почему "Cancelled"? Эта функция вызывается дважды для разного типа тикетов.

```suggestion
                f"Release issue {issue.key} summary does not contain version")
```

2022-12-29 08:13 UTC, Cookieees commented on gha/bin/release-init.py
> +        return self.repo.compare(sha1, sha2).commits
Значит я тебя ранее не так понял( Я запомнил, что ты говорил "вынеси получение коммитов в отдельную функцию и  переиспользуй её дважды". Не утверждаю, что было именно так, но я понял именно так. Можешь поправить меня? Надо или не надо всё таки выносить?

2022-12-29 08:14 UTC, Cookieees commented on gha/bin/release-init.py
> +            if repo_name != "gbl-games-portal"
Как раз вчера хотел завести очередной Enum с именем Repo. Видимо, час настал...

2022-12-29 11:28 UTC, blake-r requested changes
Зачем моё ревью если всё ещё полно "cancelled".

2022-12-29 11:28 UTC, blake-r commented on gha/bin/release-init.py
> +        cancelled_version = ''
Ты хочешь чтобы я детально каждую-каждую строчку и буковку прокомментировал?
Договорились же, что не cancelled, а просто last.

2022-12-29 11:52 UTC, Cookieees commented on gha/bin/release-init.py
> +        cancelled_version = ''
Чёрт. Это фиаско. Коммиты перемешал между ветками. Не надо было одновременно две задачи в одной репе делать

2022-12-29 16:33 UTC, Cookieees commented on gha/bin/release-init.py
> +        cancelled_version = ''
Профукал в итоге эти изменения когда переключался между ветками, но быстро вернул. А вот что заставило меня час разбираться с жирой, перечитывать свой код и читать доки(
Чтобы осознать! и найти одну строчку: мы в начале не просим в `fields` описание. А я всё пытался понять почему `AttributeError: 'PropertyHolder' object has no attribute 'description'`

2022-12-30 06:47 UTC, blake-r requested changes

2022-12-30 06:47 UTC, blake-r commented on gha/bin/release-init.py
> +        description = {'description': '\n'.join([init_description, description_appendix])}
Нет, иначе при каждом запуске будет добавляться и добавляться список коммитов. description нужно формировать полностью заново (или отложить установку поля description до этого момента вовсе - создавать тикет с пустым описанием, потом здесь уже его обновлять.

2022-12-30 06:52 UTC, Cookieees commented on gha/bin/release-init.py
> +        description = {'description': '\n'.join([init_description, description_appendix])}
ah, shit... И мало того, я почему-то решил обновлять описание last_release, а не нового

2022-12-30 07:36 UTC, blake-r requested changes

2022-12-30 07:36 UTC, blake-r commented on gha/bin/release-init.py
> +        description = {'description': '\n'.join([description_header, description_appendix])}
Это уже что-то ерунда получается - и шаблон, и кустарная строка. Добавь тогда строчку про тэг и коммит так же в шаблон description.

2022-12-30 08:48 UTC, blake-r commented on gha/bin/release-init.py
> +h3. Issues from previous last Release - %(prev_key)s (%(prev_version)s)
```suggestion
h2. Версия %(version)s

Ветка: %(head)s
Коммит: %(sha)s

h3. Изменения с версии %(prev_version)s (%(perv_key)s)
```

2022-12-30 11:43 UTC, blake-r approved these changes

2022-12-30 11:44 UTC, merged